In [5]:
from mxnet import ndarray as nd

In [6]:
nd.zeros((3,4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [7]:
nd.array([[1,2],[2,3]])


[[1. 2.]
 [2. 3.]]
<NDArray 2x2 @cpu(0)>

In [10]:
y = nd.random_normal(0,1 ,shape = (3,4))
y


[[-0.5916499   0.85860497 -0.22794183  0.20131476]
 [ 0.3500547   0.5360521   1.5194443   1.9040879 ]
 [-1.5734432  -0.14007866  0.29670075  1.3111951 ]]
<NDArray 3x4 @cpu(0)>

In [11]:
y.shape

(3, 4)

In [12]:
y.size

12

操作符


In [14]:
%pwd

'C:\\Users\\Administrator\\Gluon Folder\\demo'

In [17]:
x= nd.random_normal(0,1 ,shape = (3,4))
x


[[-1.8815191  -0.7205708  -0.3560157  -0.15963984]
 [ 1.7974477   0.19594945 -1.7376398   0.04734707]
 [ 0.14580931  0.32604915  0.4578783  -0.89425814]]
<NDArray 3x4 @cpu(0)>

In [18]:
x + y


[[-2.4731688   0.13803416 -0.58395755  0.04167493]
 [ 2.1475024   0.73200154 -0.21819544  1.951435  ]
 [-1.4276339   0.18597049  0.75457907  0.416937  ]]
<NDArray 3x4 @cpu(0)>

In [19]:
x * y


[[ 1.1132005  -0.61868566  0.08115087 -0.03213786]
 [ 0.62920505  0.10503911 -2.6402469   0.09015297]
 [-0.22942266 -0.04567253  0.13585283 -1.172547  ]]
<NDArray 3x4 @cpu(0)>

In [20]:
nd.exp(x)


[[0.15235849 0.48647448 0.7004616  0.8524507 ]
 [6.0342264  1.2164654  0.17593515 1.0484859 ]
 [1.1569755  1.3854835  1.5807166  0.40891084]]
<NDArray 3x4 @cpu(0)>

In [23]:
nd.dot(x ,y)

MXNetError: Traceback (most recent call last):
  File "c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\tensor\./dot-inl.h", line 1241
MXNetError: Check failed: L[!Ta].Size() == R[Tb].Size() (4 vs. 3) : dot shape error: [3,4] X [3,4]

In [24]:
nd.dot(x ,y.T)


[[ 0.5435279  -1.8898124   2.746451  ]
 [-0.48960412 -1.8158498  -3.3091078 ]
 [-0.09071761 -0.78120506 -1.3117894 ]]
<NDArray 3x3 @cpu(0)>

# 广播
两个ndarray形状不一样，系统尝试同一个矩阵

In [26]:
a = nd.arange(3).reshape((3,1))
b = nd.arange(2).reshape((1,2))
print("a:",a)
print("b:",b)
print("a+b" ,a + b)

a: 
[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>
b: 
[[0. 1.]]
<NDArray 1x2 @cpu(0)>
a+b 
[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>


# Numpy 的转换

In [27]:
import numpy as np

In [28]:
x = np.ones((2,3))
y = nd.array(x)
z = y.asnumpy()
print([z,y])

[array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32), 
[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>]


In [29]:
type(z)

numpy.ndarray

# 替换操作

新开一个

In [32]:
x = nd.ones((3,4))
y = nd.ones((3,4))
before = id(y)
y = y + x
id(y) == before

False

原来的旧的

In [33]:
z = nd.zeros_like(x)
before = id (z)
z[:] = x + y
id(z) == before

True

# 总结

In [ ]:
ndarray 是基础的多维数组函数